spring:
    application:
        name: stock-trading-server

    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: sa
        password: sa
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        hibernate:
            ddl-auto: none
    sql:
        init:
            mode: always

grpc:
    server:
        port: 9090
        enable-reflection: true